### ISSUE TITLE
Add support for more languages

### ISSUE THREAD

**Issue by ZedThree** [pniedzielski/doxymacs#8]
There is a patch on the original sourceforge repo for Fortran support: https://sourceforge.net/p/doxymacs/patches/12/
It needs some tidying up before it can be merged. I'll give it a shot.

In general, it would be nice to add support for other languages too. Even better would be to make it easily extensible.

**Comment by pniedzielski** [comment]
As a short-term solution, I think it would be a good idea to work off of that patch.  if you want to submit a pull request when you get a chance, I can review the patch.

In the long term, though, I think going down this particular route in order to add support for other languages isn't the right way to go about doing.  I've talked briefly with the team behind [Doxypress](http://www.copperspice.com/docs/doxypress/getting-started.html), a compatible fork of Doxygen that seems to be moving more quickly and a little more responsive, and I think having some sort of better integration there (instead of trying to patch things on top of `c++-mode`, `fortran-mode`, etc, which is essentially what we do now) would be the best way forward.  Something along the lines of a `libclang` for doxy{gen,press}.  I will need to talk further with the doxypress team about ways we can do this.

**Comment by pniedzielski** [comment]
Merged into master.
